# Schema for instropection
type __Schema {
  id: ID!
  types: [__Type!]!
  queryType: __Type!
  mutationType: __Type
  subscriptionType: __Type
  directives: [__Directive!]!
}

type __Type {
  id: ID!
  kind: __TypeKind!
  name: String
  description: String
  # List of fields
  # @includeDeprecated match {
  # false { filter(isDeprecated == true) }
  # true { filter(true) }
  # };
  fields(includeDeprecated: Boolean = false): [__Field!]
  interfaces: [__Type!]!
  possibleTypes: [__Type!]

  # List of enums
  # @includeDeprecated match {
  # false { filter(isDeprecated == true) }
  # true { filter(true) }
  # };
  enumValues(includeDeprecated: Boolean = false): [__EnumValue!]
  inputFields: [__InputValue!]
  ofType: __Type
}

type __Field {
  id: ID!
  name: String!
  description: String
  args: [__InputValue!]!
  type: __Type!
  isDeprecated: Boolean!
  deprecationReason: String
}

type __InputValue {
  id: ID!
  name: String!
  description: String
  type: __Type!
  defaultValue: String
}

type __EnumValue {
  id: ID!
  name: String!
  description: String
  isDeprecated: Boolean!
  deprecationReason: String
}

enum __TypeKind {
  SCALAR
  OBJECT
  INTERFACE
  UNION
  ENUM
  INPUT_OBJECT
  LIST
  NON_NULL
}

type __Directive {
  id: ID!
  name: String!
  description: String
  locations: [__DirectiveLocation!]!
  args: [__InputValue!]!
}

enum __DirectiveLocation {
  QUERY
  MUTATION
  SUBSCRIPTION
  FIELD
  FRAGMENT_DEFINITION
  FRAGMENT_SPREAD
  INLINE_FRAGMENT
  SCHEMA
  SCALAR
  OBJECT
  FIELD_DEFINITION
  ARGUMENT_DEFINITION
  INTERFACE
  UNION
  ENUM
  ENUM_VALUE
  INPUT_OBJECT
  INPUT_FIELD_DEFINITION
}