schema {
  query: Query
  mutation: Mutation
}

type Query {
  author(id: ID!): User!
  feed: [Post!]!
}

type User {
  " @type as i32; "
  id: ID!
  username: String!
  posts: [Post!]!
}

type Post {
  " @type as i32; "
  id: ID!
  title: String!
  author: User!
}

input PostInput {
  title: String
  author: ID
}

type Mutation {
  createPost(values: PostInput!): Post
  updatePost(id: ID!, values: PostInput!): Post
  deletePost(id: ID!): Post,
}